[ADD]NUMERIC対応
trocco-io/embulk-output-bigquery pull request #23
Opened 2022-07-05 07:53 UTC by HokutoMorita

# やったこと
inputプラグインからstring型で渡された値をColumnOptionを使ってNUMERIC型に変換する対応

## 残タスク
  - 小林さんに使用確認
    - https://github.com/primenumber-dev/n-transfer-ui/issues/9864#issuecomment-1171965495

## イシュー
  - https://github.com/primenumber-dev/n-transfer-ui/issues/9864

2022-07-11 01:40 UTC, yosuke-oka commented on Gemfile
> +# gem 'embulk'
imo: エラーが出るからバージョン指定てきなコメントのほうがわかりやすいかもです。

2022-07-11 04:31 UTC, HokutoMorita commented on Gemfile
> +# gem 'embulk'
承知しました！

2022-07-12 02:10 UTC, tksfjt1024 commented on .gitignore
> +config.yml
troccoで `config.yml` としているだけで `config.yaml` でも `hoge.yml` でもいいはずなので、git管理から外すのは本質的ではない気がするんですよね

個人の global gitignore でよしなにやるのでいい気がします

2022-07-12 02:10 UTC, tksfjt1024 commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
コメントとバージョン指定の仕方が真逆？な気がします

0.9系が使えないようバージョン指定したいですね

```suggestion
gem 'embulk', '>= 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
```

2022-07-12 04:25 UTC, HokutoMorita commented on .gitignore
> +config.yml
承知です！
それでは、こちら削除します！

2022-07-12 04:30 UTC, HokutoMorita commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
0.9系のembulkコマンドを使いたい感じです！
troccoのworkerで動いているembulkが0.9.26なので

コメントを
```
INFO: v0.9系のembulkコマンドを使う場合はエラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
```
のように修正しました。

2022-07-13 01:16 UTC, kekekenta commented
（レビュアー多かったので、抜けます

2022-07-13 01:18 UTC, tksfjt1024 commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
0.9系を使うとエラーになる、という文章に見えるのですが、まだ良くわかってないですw

どのバージョン使うとエラーになる、みたいな書き方をした方がわかりやすいかもです

2022-07-13 02:42 UTC, yosuke-oka requested changes
fjtさんのおっしゃってる通りコメント修正お願いします

2022-07-13 03:39 UTC, HokutoMorita commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
v0.9系のembulkコマンドで`embulk bundle`を実行するとエラーになります。
それを回避するために
```ruby
gem 'embulk', '< 0.10'
```
と指定する必要がある感じです。

2022-07-13 03:39 UTC, HokutoMorita commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
↑ が伝えたいことになります。

2022-07-13 03:45 UTC, HokutoMorita commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
修正しました。

2022-07-13 03:46 UTC, HokutoMorita commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
https://github.com/trocco-io/embulk-output-bigquery/pull/23/commits/edea85693cec0526477b003ddb4e40bb9fa5aaed

2022-07-13 05:24 UTC, yosuke-oka commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
ようやく理解しました。

0.9以下を使わないとエラーになるってことですね。

そもそもコメントいらない説ありますが（0.9系を使うのは見たらわかる）
書くとしたら `0.10系には非対応`とかですか？
あるいは、`0.10以上だとエラーが起きるため` とか

2022-07-13 06:04 UTC, HokutoMorita commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
確かに、コメント書かなくても良いかもですねw
コメント消しときますね！

2022-07-13 06:06 UTC, HokutoMorita commented on Gemfile
> +gem 'embulk', '< 0.10' # INFO: v0.9系のembulkコマンドの場合エラーになるのでバージョン指定してください。参考: https://zenn.dev/hiroysato/articles/957b1b4f77d549
削除しました！
https://github.com/trocco-io/embulk-output-bigquery/pull/23/commits/ae9c662dee8425325c824aedad318d4d2bc789e3

2022-07-14 00:34 UTC, tksfjt1024 approved these changes

2022-07-14 02:33 UTC, yosuke-oka approved these changes

2022-07-14 04:39 UTC, d-hrs requested changes

2022-07-14 04:39 UTC, d-hrs commented on embulk-output-bigquery.gemspec
> +  spec.version       = "0.6.14"
bugfixじゃないので、 0.7.0かな
```suggestion
  spec.version       = "0.7.0"
```

2022-07-14 04:58 UTC, HokutoMorita commented on embulk-output-bigquery.gemspec
> +  spec.version       = "0.6.14"
承知しました！

2022-07-19 08:30 UTC, HokutoMorita commented
@d-hrs 
こちらご確認よろしくお願いいたします！

2022-07-19 09:03 UTC, d-hrs approved these changes

2022-07-20 05:25 UTC, merged